[package]
name = "integer"
version = "0.0.1"
authors = ["gifnksm <makoto.nksm+github@gmail.com>"]
workspace = "../../"
edition = "2018"

[dependencies]

[features]
bigint = ["num-bigint"]
serde = ["num-bigint/serde"]

default = []
